language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install -e .
script:
  - pytest --cov=fsapi
  - mypy --strict example.py
after_success:
  - codecov
